<a href="https://colab.research.google.com/github/RaiBeirao/Estatistica_inferencial_assigment/blob/main/Assignment_08__EstatInf_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#
**Assignment - Amostragem**

O PISA (Programme for International Student Assessment) é um índice de educação gerado a cada três anos pela OCDE (Organização de Cooperação e Desenvolvimento Econômico). O PISA mede a habilidade de adolescentes de 15 anos em usar conhecimentos de leitura, matemática e ciência para lidar com problemas da vida real.
Este vídeo no Youtube [PISA - Medindo o sucesso dos estudantes em todo o mundo](https://https://www.youtube.com/watch?v=wAoBdGTEKJ8)
explica sobre como funciona a aplicação do teste. 
Assista ao vídeo e responda as questões:

### Utilize a base de dados Iris (“toy dataset” – base de dados para fins educativos) para replicar alguns tipos de amostragem.

In [ ]:
import pandas as pd
from sklearn import datasets

In [ ]:
iris_df = pd.DataFrame(datasets.load_iris().data)

In [ ]:
iris_df.columns = datasets.load_iris().feature_names

In [ ]:
iris_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

### Parte prática no Colab!

### 1. Faça uma Amostragem aleatória simples: 20 itens
### 2. Faça uma Amostragem de Julgamento: itens com “petal width” maior que 2.0
### 3. Faça uma Amostragem de Conveniência: primeiros 30 itens

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
import os
import random

Questão 1

In [ ]:
index = list(random.sample(list(range(0,len(iris_df))),k=20))
iris_df.iloc[index]

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
16                 5.4               3.9                1.3               0.4
70                 5.9               3.2                4.8               1.8
148                6.2               3.4                5.4               2.3
87                 6.3               2.3                4.4               1.3
130                7.4               2.8                6.1               1.9
118                7.7               2.6                6.9               2.3
107                7.3               2.9                6.3               1.8
60                 5.0               2.0                3.5               1.0
104                6.5               3.0                5.8               2.2
94                 5.6               2.7                4.2               1.3
105                7.6               3.0                6.6               2.1
140                6.7               3.1                5.6               2.4
40                 5.0               3.5                1.3               0.3
31                 5.4               3.4                1.5               0.4
83                 6.0               2.7                5.1               1.6
147                6.5               3.0                5.2               2.0
69                 5.6               2.5                3.9               1.1
22                 4.6               3.6                1.0               0.2
143                6.8               3.2                5.9               2.3
27                 5.2               3.5                1.5               0.2

Questão 02

In [ ]:
mask = iris_df['petal width (cm)'] > 2

index = list(random.sample(list(iris_df[mask].index),k=20))
iris_df.iloc[index]

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
120                6.9               3.2                5.7               2.3
118                7.7               2.6                6.9               2.3
112                6.8               3.0                5.5               2.1
139                6.9               3.1                5.4               2.1
109                7.2               3.6                6.1               2.5
105                7.6               3.0                6.6               2.1
104                6.5               3.0                5.8               2.2
117                7.7               3.8                6.7               2.2
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
128                6.4               2.8                5.6               2.1
145                6.7               3.0                5.2               2.3
135                7.7               3.0                6.1               2.3
144                6.7               3.3                5.7               2.5
143                6.8               3.2                5.9               2.3
115                6.4               3.2                5.3               2.3
100                6.3               3.3                6.0               2.5
148                6.2               3.4                5.4               2.3
124                6.7               3.3                5.7               2.1
114                5.8               2.8                5.1               2.4

Questão 03

In [ ]:
index = list(range(0,30))
iris_df.iloc[index]

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2
15                5.7               4.4                1.5               0.4
16                5.4               3.9                1.3               0.4
17                5.1               3.5                1.4               0.3
18                5.7               3.8                1.7               0.3
19                5.1               3.8                1.5               0.3
20                5.4               3.4                1.7               0.2
21                5.1               3.7                1.5               0.4
22                4.6               3.6                1.0               0.2
23                5.1               3.3                1.7               0.5
24                4.8               3.4                1.9               0.2
25                5.0               3.0                1.6               0.2
26                5.0               3.4                1.6               0.4
27                5.2               3.5                1.5               0.2
28                5.2               3.4                1.4               0.2
29                4.7               3.2                1.6               0.2